all:
  children:
    cisco_cloud:
      hosts:
        centos1:
          ansible_host: 198.18.134.49
        centos2:
          ansible_host: 198.18.134.50
      vars:
        ansible_user: root
        ansible_password: C1sco12345
    webservers:
      children:
        cisco_cloud:
    
