# serverless.yml

service: marsnest-user-application

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    USERS_TABLE: 'users'
    USERS_APPLICATION_TABLE: 'user_applications'
  

functions:
  hello:
    handler: app.hello
    events:
      - http: 'GET /'
  showAllApplications:
    handler: app.showAllApplications
    events:
      - http: 'GET /user_applications'
  showUserApplications:
    handler: app.showUserApplications
    events:
      - http: 'POST /user/user_applications'
  createUserApplication:
    handler: app.createUserApplication
    events:
      - http: 'POST /user_applications'